; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_MAGMAR     ; 1
	const DEX_RHYDON     ; 2
	const DEX_KANGASKHAN ; 3
	const DEX_SANDSLASH  ; 4
	const DEX_TANGELA    ; 5
	const DEX_POLIWRATH  ; 6
	const DEX_MAGNETON   ; 7
	const DEX_MEOWTH     ; 8
	const DEX_PARASECT   ; 9
	const DEX_WEEPINBELL ; 10
	const DEX_CUBONE     ; 11
	const DEX_PIKACHU    ; 12
	const DEX_ODDISH     ; 13
	const DEX_MAGIKARP   ; 14
	const DEX_JYNX       ; 15
	const DEX_RAPIDASH   ; 16
	const DEX_SEADRA     ; 17
	const DEX_MR_MIME    ; 18
	const DEX_GRAVELER   ; 19
	const DEX_ELECTRODE  ; 20
	const DEX_ARCANINE   ; 21
	const DEX_HITMONLEE  ; 22
	const DEX_POLIWHIRL  ; 23
	const DEX_HITMONCHAN ; 24
	const DEX_NIDORINA   ; 25
	const DEX_GOLEM      ; 26
	const DEX_PRIMEAPE   ; 27
	const DEX_POLIWAG    ; 28
	const DEX_VENONAT    ; 29
	const DEX_MAGMAR     ; 30
	const DEX_POLIWRATH  ; 31
	const DEX_PSYDUCK    ; 32
	const DEX_JOLTEON    ; 33
	const DEX_KINGLER    ; 34
	const DEX_GYARADOS   ; 35
	const DEX_EEVEE      ; 36
	const DEX_SLOWPOKE   ; 37
	const DEX_OMASTAR    ; 38
	const DEX_HITMONCHAN ; 39
	const DEX_WIGGLYTUFF ; 40
	const DEX_TENTACOOL  ; 41
	const DEX_HITMONLEE  ; 42
	const DEX_RHYHORN    ; 43
	const DEX_PORYGON    ; 44
	const DEX_RATICATE   ; 45
	const DEX_POLIWRATH  ; 46
	const DEX_SNORLAX    ; 47
	const DEX_BELLSPROUT ; 48
	const DEX_SEAKING    ; 49
	const DEX_NINETALES  ; 50
	const DEX_TANGELA    ; 51
	const DEX_HAUNTER    ; 52
	const DEX_VENONAT    ; 53
	const DEX_RHYDON     ; 54
	const DEX_RHYHORN    ; 55
	const DEX_VAPOREON   ; 56
	const DEX_FEAROW     ; 57
	const DEX_VILEPLUME  ; 58
	const DEX_POLIWHIRL  ; 59
	const DEX_MEWTWO     ; 60
	const DEX_KANGASKHAN ; 61
	const DEX_KABUTOPS   ; 62
	const DEX_MAGIKARP   ; 63
	const DEX_DUGTRIO    ; 64
	const DEX_EXEGGUTOR  ; 65
	const DEX_ALAKAZAM   ; 66
	const DEX_NIDOKING   ; 67
	const DEX_POLIWAG    ; 68
	const DEX_MAGMAR     ; 69
	const DEX_SCYTHER    ; 70
	const DEX_POLIWRATH  ; 71
	const DEX_ARCANINE   ; 72
	const DEX_SANDSHREW  ; 73
	const DEX_MR_MIME    ; 74
	const DEX_HITMONLEE  ; 75
	const DEX_ODDISH     ; 76
	const DEX_RATICATE   ; 77
	const DEX_BULBASAUR  ; 78
	const DEX_LICKITUNG  ; 79
	const DEX_MAGNETON   ; 80
	const DEX_PIDGEOTTO  ; 81
	const DEX_OMANYTE    ; 82
	const DEX_POLIWHIRL  ; 83
	const DEX_DITTO      ; 84
	const DEX_OMASTAR    ; 85
	const DEX_GOLDEEN    ; 86
	const DEX_HITMONLEE  ; 87
	const DEX_SANDSHREW  ; 88
	const DEX_WARTORTLE  ; 89
	const DEX_POLIWRATH  ; 90
	const DEX_RATICATE   ; 91
	const DEX_KABUTO     ; 92
	const DEX_POLIWHIRL  ; 93
	const DEX_RATICATE   ; 94
	const DEX_NIDORAN_F  ; 95
	const DEX_POLIWHIRL  ; 96
	const DEX_POLIWHIRL  ; 97
	const DEX_POLIWRATH  ; 98
	const DEX_VENOMOTH   ; 99
	const DEX_NIDORINO   ; 100
	const DEX_PRIMEAPE   ; 101
	const DEX_NIDOKING   ; 102
	const DEX_VENONAT    ; 103
	const DEX_VENONAT    ; 104
	const DEX_EEVEE      ; 105
	const DEX_HITMONCHAN ; 106
	const DEX_VICTREEBEL ; 107
	const DEX_RHYDON     ; 108
	const DEX_POLIWRATH  ; 109
	const DEX_MAGMAR     ; 110
	const DEX_MEOWTH     ; 111
	const DEX_WEEZING    ; 112
	const DEX_POLIWHIRL  ; 113
	const DEX_HITMONCHAN ; 114
	const DEX_MAGMAR     ; 115
	const DEX_SLOWBRO    ; 116
	const DEX_HITMONCHAN ; 117
	const DEX_SANDSLASH  ; 118
	const DEX_PRIMEAPE   ; 119
	const DEX_POLIWRATH  ; 120
	const DEX_TANGELA    ; 121
	const DEX_KABUTO     ; 122
	const DEX_MAGMAR     ; 123
	const DEX_MEOWTH     ; 124
	const DEX_POLIWHIRL  ; 125
	const DEX_POLIWRATH  ; 126
	const DEX_HITMONLEE  ; 127
	const DEX_NIDORINA   ; 128
	const DEX_RATICATE   ; 129
	const DEX_MAGMAR     ; 130
	const DEX_MAGMAR     ; 131
	const DEX_RATICATE   ; 132
	const DEX_POLIWRATH  ; 133
	const DEX_HITMONLEE  ; 134
	const DEX_RHYDON     ; 135
	const DEX_PARASECT   ; 136
	const DEX_HITMONLEE  ; 137
	const DEX_MAGMAR     ; 138
	const DEX_EEVEE      ; 139
	const DEX_RHYHORN    ; 140
	const DEX_MAGMAR     ; 141
	const DEX_HITMONCHAN ; 142
	const DEX_POLIWHIRL  ; 143
	const DEX_PSYDUCK    ; 144
	const DEX_HAUNTER    ; 145
	const DEX_WARTORTLE  ; 146
	const DEX_POLIWHIRL  ; 147
	const DEX_POLIWRATH  ; 148
	const DEX_POLIWHIRL  ; 149
	const DEX_MAGMAR     ; 150
	const DEX_VENONAT    ; 151

DEF NUM_POKEMON EQU const_value - 1
